### ISSUE TITLE
Wheels use raycasts instead of casting a shape

### ISSUE THREAD

**Issue by Wolfe2x7** [DAShoe1/Godot-Easy-Vehicle-Physics#1]
Hi!

I'm submitting this issue as an excuse to reach out, to ask if I can DM with you about Godot Easy Vehicle Physics. I replied to your Reddit thread as LupineVidyaDev. I'd love to get in touch.

I am delighted by what you've done with this project! I am an acquaintance of Dechode's...and the original author of parts of `wheel.gd`. 😄

The "issue": I find casting a sphere to be more robust than a ray, and there is a way to use an `AnimatableBody3D` to do it. Something to consider if you wouldn't mind chatting!

If you'd DM me on Reddit, I can send you my Discord or w/e.

Wolfe

**Comment by DAShoe1** [comment]
I can't seem to find you on Reddit, but I'd be up to chat if you want to send me a DM. I've played around with your GDSim a bit and was impressed with how smooth the vehicles behaved. I've tried using a ShapeCast3D to smooth out sudden changes over surfaces, but it just created other problems. Would be cool to hear about this solution.

**Comment by Wolfe2x7** [comment]
Great, thanks! I think Reddit is protecting you from a DM from my freshly-registered account. I deleted my old Reddit account because of it not being the friendliest website.

https://www.reddit.com/r/godot/comments/1aksjhy/updated_my_free_vehicle_controller_asset_with_new/kpb6egk/
