### ISSUE TITLE
Feature request: Example

### ISSUE THREAD

**Issue by Almenon** [DAShoe1/Godot-Easy-Vehicle-Physics#4]
Hi, thanks for open-sourcing your code! Do you have a video or videogame example? I'm curious what the physics look like and play like.

**Comment by DAShoe1** [comment]
This asset is based on the physics I use in my project here: [Jack of all Cars](https://dashoe1.itch.io/jack-of-all-cars). Also, there are 4 different examples included that handle very differently.

**Comment by Almenon** [comment]
Oh, great! Thanks!
