### ISSUE TITLE
When downloading the project there is no project.godot file

### ISSUE THREAD

**Issue by Pinkyyyy** [DAShoe1/Godot-Easy-Vehicle-Physics#7]
I downloaded the project from the Godot Asset Library and had this issue so i couldn't import it.
Decided to download as zip from github, same issue, so i had to manually download the project.godot file.

The project is also not showing up in the Godot Engine Asset Library when searching for it.

**Comment by DAShoe1** [comment]
The project is setup as an addon on the asset library, so you have to import it into an existing project. This is also the reason the download as zip feature only grabs the addons folder.

**Comment by Pinkyyyy** [comment]
I see, would be nice to make a version that is a template project, because it is a very good starting off point. Better than any on the asset library at the moment imo.
