### ISSUE TITLE
My wheels act very weird

### ISSUE THREAD

**Issue by ArtinGaming** [DAShoe1/Godot-Easy-Vehicle-Physics#9]
I'm sorry if this a stupid question for you, but my wheels rotations are messed up and the car moves weird too.

Here is a video:
https://github.com/user-attachments/assets/29c2f0de-c6e3-4876-aee4-441d23d320d6

And my settings for my car are these:
![image](https://github.com/user-attachments/assets/35510e74-1cc9-4f0f-8b09-cc948286f5ae)

![image](https://github.com/user-attachments/assets/ce6414da-b879-49f8-af97-bfc8b1c9a3e5)

![image](https://github.com/user-attachments/assets/1e19514a-f1db-4123-8e24-854762affec1)

Here is my scene tree if you need that too:
![image](https://github.com/user-attachments/assets/1953c34e-d599-4440-8c34-3c729d6f150a)

![image](https://github.com/user-attachments/assets/75f0113c-f398-4e2c-90c3-8b2012cb4d92)

Thanks so much for reading this and I love your plugin :)

**Comment by DAShoe1** [comment]
This is because you have your models are facing sideways along the x-axis. In Godot forward is along the z-axis in the negative direction. When you correct this, make sure you only rotate your model and not the rigidbody or raycast nodes.

**Comment by ArtinGaming** [comment]
Oh ok thank you so much!
